// const URL_ORGANIZATION1 = "http://";//local Now
// const URL_ORGANIZATION2 = ".ijtimaati.com/api";//local Now
// // const ENDPOINT = "http://test.conf.ijtimaati.com";//local Now
// const ENDPOINT = "http://test.app.ijtimaati.com";//local Now
// // const ENDPOINT = "http://test.ijtimaati.com";//local Now
// const BASE_URL = ENDPOINT + "/api/";
// // const USERS = 'users';
// const LOGIN = 'login';
// const PROFILE = 'profile';
// const CHANGE_PASSWORD = 'change_password';
// const FORGOT_PASSWORD = 'forget_password';
// const RESET_PASSWORD = 'reset_password';
// const DASHBOARD = 'dashboard';
// const MEETINGS = 'meetings';
// const MEETINGS_DETAILS = 'meetings/';
// const STATUS = 'status';
// const COMMITTEES = 'committees';
// const ADD_MEETINGS = 'meetings';
// const NOTE = '/note';
// const DECISIONS = '/decisions/';
// const ACTIONS = '/actions/';
// const TALIKIN_POINTS = '/talkingpoints/';
//
//
// const COMMENT = '/comment';
// const CHANGE_VOTE = '/vote/change';
// const CHANGE_STATUS = '/status/change';
// const CHANGE_STATUS_USER = '/members/changestatus';
// const CHANGE_MEETING_STATUS = '/changestatus';
// const LIBRARY = 'library';
// const FAVOURITE = 'lib-fav';
// const SHARED = 'share';
// const NEWS = 'news';
// const LIKE = 'likes';
// const UN_LIKE = 'unlike';
// const ADD_TO_FAVOURITE = 'lib-fav';
// const ADD_COMMENT_NEWS = 'comments';
// const CALENDER = 'calender';
// const AUTH_VERIFICATION = 'auth_verification';
// const TWO_AUTH_FACTOR = 'two_auth_factor';
// const String GOOGLE_MAPS_API_KEY = "AIzaSyDh_fIvktqV36c8vbnByoxqxGpLLvBtzYU";
// // const String UPDATE_FILE = "library/update";
// const String UPDATE_FILE = "library/edited_file";
// const String DELETE_COMMENT = "deleteComment";
